### ISSUE TITLE
Refgenie integration

### ISSUE THREAD

**Issue by aaron-gu** [databio/bedshift#2]
Currently the add and shift operations do not consider the reference assembly when doing perturbations, so regions can be outside of the length of the chromosome. Refgenie should have some functions to fetch reference assembly data that can solve this issues.

Will have to add a parameter to specify the reference assembly, as well as change add and shift code.

**Comment by nsheff** [comment]
this is related to #4 right? are you planning to integrate refgenie or just have it accept a chrom sizes file?

**Comment by aaron-gu** [comment]
Yes, this is related. I think accepting the chrom.sizes file is best, and leave it up to the user to decide if they want to use refgenie/other methods to manage their resources.

**Comment by nsheff** [comment]
agreed.

the advantage of integrating refgenie would be instead of this:

```
bedshift -b test.bed -l `refgenie seek hg38_primary/fasta.chrom_sizes` -s 1
```

you could do this:

```
bedshift -b test.bed -g  hg38_primary -s 1
```

we could allow both. I'll do that integration if you want.

**Comment by nsheff** [comment]
the downside is that it introduces a dependency on refgenconf

**Comment by nsheff** [comment]
Ok I've built in possibility to use refgenie directly, but it's not required.

**Comment by aaron-gu** [comment]
Thanks for adding this
