### ISSUE TITLE
size of test file

### ISSUE THREAD

**Issue by nsheff** [databio/bedshift#21]
There's a test bed file with almost 10000 regions and takes up about 1 meg of space. That's pretty big for a unit test.

Can this be pared down? or if not, can it be zipped at least?

**Comment by aaron-gu** [comment]
What is considered a reasonable size for the test BED file? I trimmed out the extra columns and the size of the file is now 240KB

**Comment by nsheff** [comment]
I mean, unit tests should be as small as possible to test the thing you're trying to test. Is 10 regions enough? 100?
