### ISSUE TITLE
Addfile bug

### ISSUE THREAD

**Issue by aaron-gu** [databio/bedshift#26]
Add from file causes ordering issue in the new regions added:

```

chrX	154377250	154377510	0			
chrX	154445076	154445336	0			
chrX	154880965	154881225	0			
chrX	154892108	154892219	0			
chrY	21154626	21154886	0			
			3	chr18	60255170	60253366
			3	chr8	75347741	75347525
			3	chr12	9596105	9595865
			3	chr21	37189188	37188872
			3	chr17	55185623	55183885
			3	chr12	122209596	122209272
			3	chr12	43190572	43190272
			3	chr7	133941061	133940568
			3	chr20	900370	900126
```

**Comment by berkuva** [comment]
Is this happening with the current version in the dev branch? I don't see the problem when I run add_from_file.

**Comment by aaron-gu** [comment]
I saw it while running from command line. Did you try it that way or with
the Python API? (this also brings up the point that we need to test the
command line interface somehow)

**Comment by berkuva** [comment]
I used command line. Can you tell me what files you are using the the bedfile and the user bedfile? Also the exact command you are using.

**Comment by aaron-gu** [comment]
I updated to the latest dev bedshift version and am still having the problem. Here is my command:

`bedshift -b /home/ec2-user/encode_tfbs//wgEncodeAwgTfbsUwHek293CtcfUniPk.narrowPeak -l /home/ec2-user/bedshift_sciquill/fig/code/pep_project/hg38.chrom.sizes -a 0.1 --addfile /home/ec2-user/bedshift_sciquill/fig/code/ALL_1000overlap_300files_segments.bed -s 0.0 -d 0.0 -r 100 -o /home/ec2-user/bedshift_sciquill/fig/code/pep_project_5trials/bedshifted//0/add1_0.bed`

Welcome to bedshift version 1.1.0-dev
Shifting file: '/home/ec2-user/encode_tfbs//wgEncodeAwgTfbsUwHek293CtcfUniPk.narrowPeak'
Params:
  chrom.sizes file: /home/ec2-user/bedshift_sciquill/fig/code/pep_project/hg38.chrom.sizes
  shift:
    shift rate: 0.0
    shift mean distance: 0.0
    shift stdev: 150.0
  shift regions from file: None
  add:
    rate: 0.1
    add mean length: 320.0
    add stdev: 30.0
    add file: /home/ec2-user/bedshift_sciquill/fig/code/ALL_1000overlap_300files_segments.bed
  cut rate: 0.0
  drop rate: 0.0
  drop regions from file: None
  merge rate: 0.0
  outputfile: /home/ec2-user/bedshift_sciquill/fig/code/pep_project_5trials/bedshifted//0/add1_0.bed
  repeat: 100
  yaml_config: None

**Comment by aaron-gu** [comment]
I've confirmed it's an issue with the way the code is reading the header of /home/ec2-user/bedshift_sciquill/fig/code/ALL_1000overlap_300files_segments.bed

PR coming
