### ISSUE TITLE
Write doc guides

### ISSUE THREAD

**Issue by aaron-gu** [databio/bedshift#3]
guide ideas:
- how to make a test set from one file for similarity metric
- how to alter multiple files: python and bash way
- how to create a randomly generated bed file

**Comment by nsheff** [comment]
are you still going to write these doc guides?

**Comment by aaron-gu** [comment]
the first one is done, I can work on the second and third one

**Comment by aaron-gu** [comment]
PR #7

**Comment by aaron-gu** [comment]
Doc guides for Add from file, drop from file, and yaml_config are needed. @hyunjaecho94 for visibility

**Comment by nsheff** [comment]
@hyunjaecho94 what's status here?

**Comment by aaron-gu** [comment]
finished by me
