### ISSUE TITLE
bug in calculation of regions changed?

### ISSUE THREAD

**Issue by nsheff** [databio/bedshift#5]
I'm confused as the "X regions changed" notification at the end of every run appears incorrect. For example, I have 1 region and I run bedshift, and it says: 5 regions changed"

```
bedshift -b test.bed -l `refgenie seek hg38_primary/fasta.chrom_sizes` -s 1 
welcome to bedshift
Shifting file: 'test.bed'
Params:
    chrom.sizes file: /home/nsheff/code/refgenie_sandbox/hg38_primary/fasta/default/hg38_primary.chrom.sizes
    shift rate: 1.0
        shift mean distance: 0.0
        shift stdev: 150.0
    add rate: 0.0
        add mean length: 320.0
        add stdev: 30.0
    add regions from file: None
    cut rate: 0.0
    drop rate: 0.0
    merge rate: 0.0
    outputfile: None
    repeat: 1
            
The output bedfile located in bedshifted_test.bed has 1 regions. The original bedfile had 1 regions.
5 regions changed
nsheff@zither:~/garage/bedshift_test$ cat test.bed
chrX	1	1000
```
actually, no regions were changed, look:

```
cat bedshifted_test.bed 
chrX	1	1000	0
```

**Comment by nsheff** [comment]
so this appears to be 2 separate bugs:

1. why does it say the wrong number of regions were changed.
2. why is it not shifting the region when I put the shift rate at 100%?

**Comment by nsheff** [comment]
another related issue: when I use repeat, every number is the same:

```
Shifting file: 'oct4.bed'
Params:
  chrom.sizes file: /home/nsheff/code/refgenie_sandbox/hg38_primary/fasta/default/hg38_primary.chrom.sizes
  shift:
    shift rate: 0.3
    shift mean distance: 0.0
    shift stdev: 150.0
  add: 
    rate: 0.15
    add mean length: 320.0
    add stdev: 30.0
    add file: oct4.bed
  cut rate: 0.0
  drop rate: 0.0
  merge rate: 0.0
  outputfile: local_output/add_shift9.bed
  repeat: 10

The output bedfile located in local_output/rep1_add_shift9.bed has 8382 regions. The original bedfile had 7289 regions.
3279 regions changed
The output bedfile located in local_output/rep2_add_shift9.bed has 8382 regions. The original bedfile had 7289 regions.
3279 regions changed
The output bedfile located in local_output/rep3_add_shift9.bed has 8382 regions. The original bedfile had 7289 regions.
3279 regions changed
The output bedfile located in local_output/rep4_add_shift9.bed has 8382 regions. The original bedfile had 7289 regions.
3279 regions changed
The output bedfile located in local_output/rep5_add_shift9.bed has 8382 regions. The original bedfile had 7289 regions.
3279 regions changed
The output bedfile located in local_output/rep6_add_shift9.bed has 8382 regions. The original bedfile had 7289 regions.
3279 regions changed
The output bedfile located in local_output/rep7_add_shift9.bed has 8382 regions. The original bedfile had 7289 regions.
3279 regions changed
The output bedfile located in local_output/rep8_add_shift9.bed has 8382 regions. The original bedfile had 7289 regions.
3279 regions changed
The output bedfile located in local_output/rep9_add_shift9.bed has 8382 regions. The original bedfile had 7289 regions.
3279 regions changed
The output bedfile located in local_output/rep10_add_shift9.bed has 8382 regions. The original bedfile had 7289 regions.
3279 regions changed
```

The number of regions changed should be random each time, so it shouldn't be the same number changed, right? I mean, I know from above that this number is inaccurate anyway, but if it is in fact changing the same number each time, is that another problem?

**Comment by aaron-gu** [comment]
I changed the way that the perturbed regions were selected. Before, it would iteratively examine every region and decide by the user inputted chance if that region was going to be modified. That method was slow since it had to iterate through the whole file multiple times. The new method first finds the number of regions that are going to be changed (for example 5% of 20000 regions = 1000 regions) then randomly selects 1000 regions from the BED file to change. Therefore if the input is 5%, then 1000 regions will change every time.

**Comment by nsheff** [comment]
> I changed the way that the perturbed regions were selected. Before, it would iteratively examine every region and decide by the user inputted chance if that region was going to be modified. That method was slow since it had to iterate through the whole file multiple times. The new method first finds the number of regions that are going to be changed (for example 5% of 20000 regions = 1000 regions) then randomly selects 1000 regions from the BED file to change. Therefore if the input is 5%, then 1000 regions will change every time.

Ok, makes sense -- but the set of 1000 regions differs at least?

**Comment by aaron-gu** [comment]
yes

**Comment by aaron-gu** [comment]
PR #6
